
service: worktrackerbackend

app: worktrackerbackend-app
org: ryanbrandt1996

provider:
  name: aws
  runtime: nodejs10.x

 you can overwrite defaults here
  stage: dev
  region: us-east-1

plugins:
  - serverless-offline
  - serverless-plugin-stage-variables
  - serverless-plugin-warmup

functions:
  addUserToCompany:
    handler: api/users/handler.addToCompany
      - http:
          method: post
          cors: true
          path: /users
          method: post
  recordsByUser:
      handler: api/records/handler.byUser
        - http:
            method: get
            cors: true
            path: /records
          request:
            parameters:
              querystrings:
                userId: true
              
